apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: 4.7.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 1m
  interval: 5m
  values:
    controller:
      ingressClass: nginx
      allowSnippetAnnotations: true
      podAnnotations:
        # Do not redirect inbound traffic to Envoy.
        traffic.sidecar.istio.io/includeInboundPorts: ""
        traffic.sidecar.istio.io/excludeInboundPorts: "80,443"
        # Exclude outbound traffic to kubernetes master from redirection.
        traffic.sidecar.istio.io/excludeOutboundIPRanges: "10.96.0.1/32"
        # sidecar.istio.io/inject: "true"
      admissionWebhooks:
        patch:
          podAnnotations:
            sidecar.istio.io/inject: "false"
      replicaCount: 2
      service:
        enabled: true
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
    env:
      - name: GODEBUG
        value: "x509ignoreCN=0"
